let userName = prompt("what is your name");
alert("Welcome " + userName);
console.log("Username: " + userName);
let num1 = prompt("enter first number");
let num2 = prompt("enter second number");
num1 = Number(num1);
num2 = Number(num2);
let sum = num1 + num2;
alert("Addition: " + sum);
console.log("Addition: " + sum);
